services:
  kernel.listener.body_listener.json:
    class: Fer\HelpersBundle\EventListener\BodyListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 10}

  app.param_converter.array2command_converter:
    class: Fer\HelpersBundle\ParamConverter\Array2CommandConverter
    arguments: [ @validator ]
    tags:
      - { name: request.param_converter, converter: array2command_converter }

  app.rest_exception_listener:
    class: Fer\HelpersBundle\EventListener\RestExceptionListener
    arguments: [ @tbbc_rest_util.error.error_resolver, %twig.exception_listener.controller%, @logger ]
    tags:
     - { name: kernel.event_subscriber }
     - { name: monolog.logger, channel: request}

  app.validation_error_factory:
    class: Fer\HelpersBundle\Error\ValidationErrorFactory
    tags:
      - {name: tbbc_rest_util.error_factory}

  app.validator.choice_from_config:
    class: Fer\HelpersBundle\Validator\Constraints\ChoiceFromConfigValidator
    arguments: [@service_container]
    tags:
      - { name: validator.constraint_validator, alias: 'choice_from_config' }